version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GoGreen@123
    restart: always
    ports:
      - "5432:5432"
    volumes:
       - postgres_catalog:/var/lib/postgresql/data/    