# For more info on HTTP files go to https://aka.ms/vs/httpfile

@host = https://localhost:5050
POST {{host}}/products
Content-Type: application/json


{
    "Name":"Carter module",
    "Category":["api"],
    "Description":"api development",
    "ImageFile":"as",
    "Price":100
}

###
GET {{host}}/products?pagenumber=2&pageSize=5

###

GET {{host}}/products/{018f9036-5e24-48ec-93e4-25207e8e7302}

###


GET {{host}}/products/category/api1

###
PUT {{host}}/products
Content-Type: application/json

{
   "Id":"018f9036-5e24-48ec-93e4-25207e8e7302",
    "Name":"Carter module",
    "Category":["api1","api2"],
    "Description":"api development",
    "ImageFile":"",
    "Price":100
}

###

DELETE {{host}}/products/{018f9036-5e24-48ec-93e4-25207e8e7302}

### 
//Health check
GET {{host}}/health