# For more info on HTTP files go to https://aka.ms/vs/httpfile

@host = https://localhost:5050
POST {{host}}/products
Content-Type: application/json


{
    "Name":"Carter module",
    "Category":["api"],
    "Description":"api development",
    "ImageFile":"as",
    "Price":100
}

###
GET {{host}}/products?pagenumber=2&pageSize=5

###

GET {{host}}/products/{018f9036-5e24-48ec-93e4-25207e8e7302}

###


GET {{host}}/products/category/api1

###
PUT {{host}}/products
Content-Type: application/json

{
   "Id":"018f9036-5e24-48ec-93e4-25207e8e7302",
    "Name":"Carter module",
    "Category":["api1","api2"],
    "Description":"api development",
    "ImageFile":"",
    "Price":100
}

###

DELETE {{host}}/products/{018f9036-5e24-48ec-93e4-25207e8e7302}

### 
//Health check
GET {{host}}/health

###

@host1 = https://localhost:5051
POST {{host1}}/basket
Content-Type: application/json

{
    "cart":{
      "UserName":"sachinkumar@gmail.com",
      "items":[{
        "ProductId":"018f9036-5e24-48ec-93e4-25207e8e7302",
        "ProductName":"IPhone X",
        "Price":100,
        "Quantity":1,
        "color":"red"
    },
      {
        "ProductId":"018f9036-5e24-48ec-93e4-25207e8e7303",
        "ProductName":"IPhone X",
        "Price":1000,
        "Quantity":2,
        "color":"green"
      }
    ]
    }
}

###
GET {{host1}}/basket/sachinkumar@gmail.com

###

POST {{host1}}/basket/checkout
Content-Type:application/json

{"basketcheckoutDto":{
    "UserName": "sachinkumar@gmail.com",
    "CustomerId": "189dc8dc-990f-48e0-a37b-e6f2b60b9d70",
    "TotalPrice": 2100,
    "FirstName": "John",
    "LastName": "Doe",
    "EmailAddress": "sachinkumar@gmail.com",
    "AddressLine": "test",
    "Country": "test",
    "State": "test",
    "ZipCode": "0000",
    "CardName": "test",
    "CardNumber": "test",
    "Expiration": "12/25",
    "CVV": "123",
    "PaymentMethod": 1
}
}